# Generated by Django 3.0.2 on 2020-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllaboutSikkim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='')),
                ('bg_heading', models.CharField(max_length=10)),
                ('heading', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('sub_heading1', models.TextField()),
                ('image2', models.ImageField(upload_to='')),
                ('sub_heading2', models.TextField()),
            ],
            options={
                'verbose_name': 'All About Sikkim',
                'verbose_name_plural': 'All About Sikkim',
                'db_table': 'tbl_aboutsikkim',
                'managed': True,
            },
        ),
    ]
