# Generated by Django 3.0.2 on 2020-02-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_allaboutsikkim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allaboutsikkim',
            options={'managed': True, 'verbose_name': 'All About Sikkim', 'verbose_name_plural': 'Add About Sikkim'},
        ),
    ]
