# Generated by Django 3.0.2 on 2020-01-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'managed': True, 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': 'Post', 'verbose_name_plural': 'Ayub'},
        ),
    ]
