# Generated by Django 3.0.2 on 2020-01-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200126_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': 'Post', 'verbose_name_plural': 'Add Blog'},
        ),
    ]
