# Generated by Django 3.0.2 on 2020-02-15 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200215_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allaboutsikkim',
            old_name='heading',
            new_name='heading2',
        ),
        migrations.AddField(
            model_name='allaboutsikkim',
            name='heading1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
