# Generated by Django 3.0.2 on 2020-02-15 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200215_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='allaboutsikkim',
            name='heading3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
